### ISSUE TITLE
LIS reconstruccion

### ISSUE THREAD

**Issue by GustavoMeza** [GustavoMeza/icpc-notebook#9]
¿Podemos agregar la reconstrucción del LIS?

**Comment by EfrenGonzalezG** [comment]
¿A qué te refieres con reconstrucción?

**Comment by GustavoMeza** [comment]
y que si no solo quiero saber la longitud de la LIS, pero tambien la LIS tal cual

**Comment by EfrenGonzalezG** [comment]
El Lis regresa un vector

**Comment by GustavoMeza** [comment]
Para el caso {1, 2, 0} regresa {1, 0}
